/* dtreg.h - Document Type registry */

/* WARNING - this file is automaticly generated by ../doctypes/dtconf.c */

#include "../doctype/doctype.h"

#include <stdlib.h>
#include "defs.h"
#include "stringx.h"
#include "mdtrec.h"
#include "mdt.h"
#include "idbobj.h"
#include "iresult.h"
#include "irset.h"
#include "dtreg.h"

DTREG::DTREG(PIDBOBJ DbParent) {
	Db = DbParent;
	DtDocType = new DOCTYPE(Db);
	DtSIMPLE = 0;
	DtCOLONDOC = 0;
	DtKEYWORD = 0;
	DtSITEDOC = 0;
}

PDOCTYPE DTREG::GetDocTypePtr(unsigned char DocType) {
	if (DocType == 0) {
		return DtDocType;
	}
	switch(DocType) {
	case DOC_TYPE_SIMPLE:
		if (!DtSIMPLE) {
			DtSIMPLE = new SIMPLE(Db);
		}
		return DtSIMPLE;
		break;
	case DOC_TYPE_COLONDOC:
		if (!DtCOLONDOC) {
			DtCOLONDOC = new COLONDOC(Db);
		}
		return DtCOLONDOC;
		break;
	case DOC_TYPE_KEYWORD:
		if (!DtKEYWORD) {
			DtKEYWORD = new KEYWORD(Db);
		}
		return DtKEYWORD;
		break;
	case DOC_TYPE_SITEDOC:
		if (!DtSITEDOC) {
			DtSITEDOC = new SITEDOC(Db);
		}
		return DtSITEDOC;
		break;
	default:
		return DtDocType;
		break;
	}
}

unsigned char DTREG::GetDocTypeFromString(STRING DocType) {
	if (DocType == "SIMPLE") {
		return DOC_TYPE_SIMPLE;
	}
	if (DocType == "COLONDOC") {
		return DOC_TYPE_COLONDOC;
	}
	if (DocType == "KEYWORD") {
		return DOC_TYPE_KEYWORD;
	}
	if (DocType == "SITEDOC") {
		return DOC_TYPE_SITEDOC;
	}
	return DOC_TYPE_INVALID;
}

char * DTREG::GetStringFromDocType(unsigned char dt) {
	if (dt == DOC_TYPE_SIMPLE) {
		return "SIMPLE";
	}
	if (dt == DOC_TYPE_COLONDOC) {
		return "COLONDOC";
	}
	if (dt == DOC_TYPE_KEYWORD) {
		return "KEYWORD";
	}
	if (dt == DOC_TYPE_SITEDOC) {
		return "SITEDOC";
	}
	return "INVALID";
}

char * DTREG::GetDocTypeList() const {
	return("SIMPLE COLONDOC KEYWORD SITEDOC");
}

DTREG::~DTREG() {
	delete DtDocType;
	if (DtSIMPLE) {
		delete DtSIMPLE;
	}
	if (DtCOLONDOC) {
		delete DtCOLONDOC;
	}
	if (DtKEYWORD) {
		delete DtKEYWORD;
	}
	if (DtSITEDOC) {
		delete DtSITEDOC;
	}
}
